apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-sonny-core
  labels:
    app: ai-sonny
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-sonny
  template:
    metadata:
      labels:
        app: ai-sonny
    spec:
      containers:
        - name: ai-sonny
          image: {AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/usai-sonny-core:ai-latest
          ports:
            - containerPort: 9000
          readinessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ai-sonny-svc
spec:
  selector:
    app: ai-sonny
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: ClusterIP
